### ISSUE TITLE
consider ignoring associations with conditions/where

### ISSUE THREAD

**Issue by jenseng** [jenseng/immigrant#19]
If an association has a `where` scope (or `conditions` in rails 3.x), immigrant will infer a foreign key for it (assuming the various other checks pass). It will at least ignore `dependent: :delete` and friends, since that may not be safe to bring into the foreign key.

Generally this behavior is fine, but there are some cases where you can't actually generate a foreign key. Consider the following example:

```ruby
class SettingValue
  belongs_to :setting, { where(deleted_at: nil) },
             foreign_key: :name, primary_key: :name
end
```

with an index in the db like so:

```
"index_settings_on_name" UNIQUE, btree (name) WHERE deleted_at IS NULL
```

`name` is guaranteed to be unique for non-deleted values, but it's not a true primary key. Since you could have deleted values with a colliding name, you can't create a foreign key for it... you'll get an error like:

```
PG::InvalidForeignKey: ERROR:  there is no unique constraint matching given keys for referenced table "settings"
```

Perhaps one approach would be to skip these associations with a non-standard `primary_key`? Or maybe we could otherwise detect from the schema/indexes the fact that the "primary_key" may not actually be unique across the parent table?

**Comment by dkubb** [comment]
Yeah, this bit me today. Immigrant identified [this](https://github.com/MountainRoseHerbs/spree/blob/2-3-stable-mrh/core/app/models/spree/payment.rb#L13-L14) as in need of a foreign key for `source_id`, which is part of a polymorphic association and not a valid candidate for a DB foreign key.

**Comment by jenseng** [comment]
@dkubb d'oh, yeah I've been [meaning to track that down](https://github.com/jenseng/immigrant/issues/2#issuecomment-49123194) ... immigrant should [definitely skip polymorphic associations](https://github.com/jenseng/immigrant/blob/ab1ce990423be4695a2175e65593fcb150d42f25/test/immigrant_test.rb#L355), whether set up as a belongs_to or a has_many. I'll add some more tests to mimic Spree's associations, then we can know for sure if it's an immigrant issue, or if Spree is doing something weird ActiveRecord-wise.

**Comment by jenseng** [comment]
I added a test locally and still couldn't reproduce the issue, but now I think I understand why. Looks like [you changed that line](https://github.com/MountainRoseHerbs/spree/commit/3dbe7bd4fd16eba5e32ae24fa8f75b0f41c6da61) just 15 min after your comment above :smile: 

On the old code, immigrant would indeed have tried to make a foreign key before (i.e. the issue outlined in this ticket), but now it shouldn't now that the association is polymorphic. Does that match what you're seeing? Or is immigrant still trying to create that key after your change?

**Comment by dkubb** [comment]
> I added a test locally and still couldn't reproduce the issue, but now I think I understand why. Looks like you changed that line just 15 min after your comment above

@jenseng yeah, we have a fork of spree that we apply changes to and eventually upstream them when we've fully tested them out.

> On the old code, immigrant would indeed have tried to make a foreign key before (i.e. the issue outlined in this ticket), but it shouldn't now that the association is polymorphic. Does that match what you're seeing? Or is immigrant still trying to create that key after your change?

Yeah, immigrant works properly with this code now. I made the change so that we'd work within immigrant's expectations because it was fast and something within our control; we didn't want to make any assumptions about your changing immigrant.

I think if immigrant *did* filter out associations with `where` clauses, it would've filtered out this specific association too. Although a bigger problem with this code is that it *should* have been defined as a proper polymorphic association anyway.
