### ISSUE TITLE
`rake immigrant:check_keys` fails even after adding new script

### ISSUE THREAD

**Issue by RichardJECooke** [jenseng/immigrant#25]
Following the readme, I ran  `rails generate immigration AddKeys`, which added the migration script to my db folder.

And then I ran `rake immigrant:check_keys` and got the same list of missing keys that immigrant just generated and added to the script.

Why doesn't the check_keys function take the new script into account and stop reporting warnings??

**Comment by twe4ked** [comment]
I assume you haven't run the migration? I assume `check_keys` will be looking at the local database not the migrations folder.

**Comment by RichardJECooke** [comment]
Oh, I thought it used the scripts only. When I get all my corrupt data cleaned away I'll try run it again and see if the warnings are gone. Thank you.

**Comment by jenseng** [comment]
Yup, @twe4ked is correct, immigrant compares the database's current foreign keys with the model associations... it doesn't evaluate any outstanding migrations. If you discover any issues around `check_keys` incorrectly reporting on the models <-> foreign keys, feel free to reopen this ticket w/ more details / repro steps.
