### ISSUE TITLE
Generating foreign key vs references

### ISSUE THREAD

**Issue by oyeanuj** [jenseng/immigrant#30]
Hi @jenseng, thank you for this library! I am curious, conceptually, why do the migrations generate `add_foreign_key` commands over `add_reference`, since often semantically `references` may be more appropriate than just `foreign_key`?

Is it not to be too prescriptive about indexing?

**Comment by jenseng** [comment]
Unless I'm mistaken, doesn't `add_reference` add a column? Immigrant is intended for those cases where you want to add missing foreign keys to existing columns.

It's also that way for historical reasons, as immigrant was initially an add-on to [foreigner](https://github.com/matthuhiggins/foreigner) before rails had built-in support for foreign keys, so `add_foreign_key` used to be the only way to create one.

I'd also agree with your point about not wanting to be too prescriptive, i.e. I often find scenarios where I want a foreign key but no index (e.g. low cardinality, or query usage patterns would never use the index, etc).

I'll go ahead and close this ticket, though I'd be willing to consider a pull request to make the generated migration also include `add_index` calls (would have to be opt-in though).
